### ISSUE TITLE
Moscow

### ISSUE THREAD

**Issue by Diokuz** [bluesmoon/node-geoip#105]
Here is a result of my lookup:

```
{ range: [ 1365213184, 1365214975 ],
  country: 'RU',
  region: '',
  city: '',
  ll: [ 55.75, 37.6166 ],
  metro: 0 }
```
It is a center of Moscow, but no city or region provided.

**Comment by bluesmoon** [comment]
Can you check against the online MaxMind database at https://www.maxmind.com/en/geoip-demo and tell me what results you get (I cannot check since you haven't provided the IP).

Also, make sure you have the latest database installed.  You'll need to run the update script once a month to keep your database up to date.

**Comment by Diokuz** [comment]
```bash
cd ./node_modules/geoip-lite
npm run updatedb
```

my ip is `81.95.130.210`

the result is
```bash
{ range: [ 1365213184, 1365214975 ],
  country: 'RU',
  region: '',
  city: '',
  ll: [ 55.75, 37.6166 ],
  metro: 0 }
```

it is not only my ip problem, we have a lot of them (also in Novosibirsk).

**Comment by bluesmoon** [comment]
This is not a problem with the library.  The free database does not contain full resolution for your IP, but the commercial database does.  If you're willing, you can get the commercial geoip city database from MaxMind in csv format.  Unfortunately this opensource project cannot keep the commercial database in the repository.

**Comment by Diokuz** [comment]
mkay

**Comment by bluesmoon** [comment]
Sorry I couldn't be more help
