### ISSUE TITLE
keep the db updated on heroku

### ISSUE THREAD

**Issue by shaharsol** [bluesmoon/node-geoip#160]
when i deploy my app that uses geoip-lite to heroku, it will `npm install geoip-lite` on my behalf. Do you happen to know how I can run updatedb during heroku deployment and is there any way to keep it updated so it won't run all over again with any new deployment?

**Comment by bluesmoon** [comment]
You could maintain your own package that contains data files and has a dependency on our page. Push that to npm and instead of pulling our package, pull yours and let npm pull ours as a dependency.  That way you can release a new version once a month and all your deployments from that point on will get the latest data files.

We used to have `updatedb` run automatically after npm installed, but it would fail for too many people running in a cloud environment with not enough RAM leaving them with no install at all.

**Comment by gtebbutt** [comment]
Depending on your needs, you can also just add an `updatedb` command to your `Procfile` or in your `npm start` definition (https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type). 

It will run redundantly on every deploy, but there's no manual input or maintenance needed - for us, that was worth the extra minute or so it adds to the build time.

**Comment by Ashoat** [comment]
Ideally I'd like a way for the node runtime to call `updatedb` programmatically. It could then reload the resultant updated data programmatically, which would make sure the data stays updated even if a deploy doesn't happen for a while.

What would be the best practice for this sort of thing? Just calling `require('geoip-lite/scripts/updatedb.js')` seems convenient, but I'm worried that it might allocate memory that doesn't get freed after it's done, and that it might not work successfully if called multiple times. Would spawning a shell running the `updatedb` npm script be a better idea?

In the perfect world, there would be a way to stage the updated data so that if the `updatedb` fails for whatever reason, we could roll back the update. But I imagine that sort of failure would be unlikely to happen on a sufficiently provisioned server.

**Comment by ar2rsawseen** [comment]
In overall, yes to do upgrade, you need to run updatedb.js script
Running it using require would run it only once, so spawning a separate process is a better idea.
https://github.com/bluesmoon/node-geoip#ways-to-update-data

After update is done, you also need to reload the data in memory from the files.
This can be done either with watching file for updates:
https://github.com/bluesmoon/node-geoip#automatic-start-and-stop-watching-for-data-updates

Or programmatically reload data after your update process is done:
https://github.com/bluesmoon/node-geoip#programmatically

About staging, I guess new files can be generated in a temporary directory and then copied over existing files. Just need to come up with the best way to verify if DB is correct, because it could have the same problem that we have with tests. The results change after db update 😄

**Comment by Ashoat** [comment]
Hmm. `node-schedule` does not initialize a new process. I have it set up to run in [the `cluster.isMaster` Node process](https://github.com/Ashoat/squadcal/blob/master/server/src/cron/cron.js).

I suppose the issue here is that the “slave” Node processes won’t get the update just because the “master” called `geoip.reloadData`? If so my options are either to use IPC between the processes to trigger `geoip.reloadData` on all of them, or to call `startWatchingDataUpdate` on all of them. I probably lean to the former out of efficiency/performance concerns, although I’m not too familiar with the performance characteristics of the file-watching logic, or how it scales to multiple threads.

**Comment by bluesmoon** [comment]
Hi, just a note about terminology in this repo, we prefer not to use master-slave, but primary-secondary instead. In this case it's outside your control as the node developers have unfortunately chosen to use it as an identifier in their code and documentation so developers are forced to use it, but I need to state this here to be clear and consistent about our choices on this project.

**Comment by Ashoat** [comment]
Understood. I also prefer that terminology, which is why I kept my uses above in quotes.

**Comment by Ashoat** [comment]
Following up on this, in case anybody else finds my code examples useful - [this commit](https://github.com/Ashoat/squadcal/commit/1ec8e47595f60091f5e88df9197dd3b3b32b8a31) makes sure that all cluster members reload their GeoIP data after the cluster leader/primary updates it.

**Comment by grantmk** [comment]
> Hi, just a note about terminology in this repo, we prefer not to use master-slave, but primary-secondary instead. In this case it's outside your control as the node developers have unfortunately chosen to use it as an identifier in their code and documentation so developers are forced to use it, but I need to state this here to be clear and consistent about our choices on this project.

Not a personal attack on you, just a general comment:

I doubt that even **_one single developer_** thinks of slavery when 'Master Slave' is mentioned in software contexts. Please can we dispense with this George Orwell double-think new-speak stupidity. Software design is hard enough without adding language complexity to the process!

**Comment by bluesmoon** [comment]
You doubt it, but you're wrong. Please speak to every developer on the planet or at least a representative sample, and come back with your statistically significant results. If you really are a skilled developer, you'd know to follow the scientific method.

**Comment by grantmk** [comment]
Ooh, someone gets a little angry when someone else won't bend to his will. Must be fun working with you! 

In fact, I'd imagine that being in your team would be rather like being in a 'Master - Slave' arrangement...

**Comment by bluesmoon** [comment]
Do you really believe that software developers have no choice when it comes to where they work and who they work for or do you think that slavery comes with a paycheck and a benefits package?
