### ISSUE TITLE
Range out of error

### ISSUE THREAD

**Issue by geekfarmer** [bluesmoon/node-geoip#197]
geoip-lite 

version 1.4.0

It is working sometimes and sometimes giving error.

ERROR:

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 59400892. Received 62533861
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readInt32BE (internal/buffer.js:361:5)
    at lookup4 (/var/app/current/node_modules/geoip-lite/lib/geoip.js:114:31)
    at Object.lookup (/var/app/current/node_modules/geoip-lite/lib/geoip.js:461:11)

**Comment by ar2rsawseen** [comment]
Hello, in most cases OUT OF RANGE error is due to mismatch of data and version of the library (for example padding changes in the new version, but you are using it on older DB with old padding)

And in most cases, it is solvable with data updates.

If you still run into this issue after an update, can you try to log the IP address and provide it here for testing purposes? Feel free to reopen the issue in such case  :)
