### ISSUE TITLE
Feature Request: Continent Codes

### ISSUE THREAD

**Issue by msimerson** [bluesmoon/node-geoip#47]
Although only mildly helpful for humans, having continent codes are very useful for bayesian classifiers.  For most cases, connections from continents other than their own are suspect.

**Comment by BenjaminRH** [comment]
:+1:

**Comment by Rickgbw** [comment]
👍

**Comment by subversivo58** [comment]
:+1: This is a great need to filter connections, distribute applications, or provide content on demand

**Comment by bluesmoon** [comment]
If anyone wants to build this, i'll merge it in.

**Comment by typpo** [comment]
@bluesmoon As far as I can tell continent is not directly available in any of the Maxmind geoip databases.

But I did find this mapping provided by Maxmind from ISO 3166 country code to continent code:  https://dev.maxmind.com/geoip/legacy/codes/country_continent/

(It appears the mapping is also included statically in the C library implementation: https://github.com/maxmind/geoip-api-c/blob/a16267aec08fe9e9f7875b8d8b2f3d2cc154e51e/libGeoIP/GeoIP.c#L542)

So what I'd like to do is use the Maxmind country code->continent mapping and perform lookups based on that.  I'd just include the CSV statically in the `data/` directory.  Let me know if this sounds ok to you and I'll submit a PR.

**Comment by bluesmoon** [comment]
Sure, go ahead.  I would have preferred if there were a separate library to map country to continent since it seems like something usable outside of geo-ip as well, but if there isn't then this is fine.

My concern with any kind of continent mapping is the complication with Turkey which is simultaneously in Asia and Europe or countries like France or the Netherlands which are primarily in Europe, but also have portions in the Caribbean and elsewhere.
